USE SPCLINICALGROUP
GO

--MOSTRA TODOS OS CONTEÚDOS DAS TABELAS
SELECT * FROM CLINICA
SELECT * FROM ESPECIALIDADE
ORDER BY idEspecialidade

SELECT * FROM TipoUsuario
SELECT * FROM USUARIO
SELECT * FROM SITUACAO
SELECT * FROM CONSULTA
SELECT * FROM MEDICO

--MOSTRA TODAS AS INFORMAÇÕES DOS PACIENTES
SELECT Nome, Email, DataNasc, RG, CPF, Telefone, Endereco, idUsuario FROM PACIENTE
INNER JOIN USUARIO ON PACIENTE.idPaciente = USUARIO.idPaciente

--MOSTRA INFORMAÇÕES DOS MÉDICOS, E A QUAL CLINICA PERTENCEM
SELECT Medico.idMedico,Nome,Email,CRM,Especialidade,idUsuario,CLINICA.idClinica,NomeClinica,endereco FROM MEDICO
INNER JOIN Clinica ON MEDICO.idClinica = CLINICA.idClinica
INNER JOIN USUARIO ON MEDICO.idMedico = USUARIO.idMEDICO
INNER JOIN ESPECIALIDADE ON MEDICO.idEspecialidade = ESPECIALIDADE.idEspecialidade

--MOSTRA INFORMAÇÕES DOS USUARIOS
SELECT idUsuario, Tipo, Nome, Email, DataNasc, Telefone, RG, CPF, Endereco FROM USUARIO
LEFT JOIN MEDICO M ON USUARIO.idMedico = M.idMedico
LEFT JOIN PACIENTE P ON USUARIO.idPaciente = P.idPaciente
LEFT JOIN TipoUsuario T ON USUARIO.idTipoUsuario = T.idTipoUsuario

--MOSTRA AS CONSULTAS E DADOS ESSENCIAIS
SELECT P.Nome Paciente , M.Nome Médico, DataConsulta 'Data da Consulta', Situacao FROM CONSULTA
LEFT  JOIN USUARIO P ON CONSULTA.idPaciente = P.idPaciente
LEFT JOIN USUARIO M ON CONSULTA.idMedico = M.idMedico
INNER JOIN SITUACAO ON CONSULTA.idSituacao = SITUACAO.idSituacao

--MOSTRA TODAS AS CONSULTAS NOME E DETALHES DOS PACIENTES, MEDICOS, DATA DA CONSULTA E SITUACAO
SELECT P.Nome Paciente , CPF, Telefone, M.Nome Médico, Especialidade, DataConsulta 'Data da Consulta', Situacao FROM CONSULTA
LEFT  JOIN USUARIO P ON CONSULTA.idPaciente = P.idPaciente
LEFT JOIN USUARIO M ON CONSULTA.idMedico = M.idMedico
INNER JOIN SITUACAO ON CONSULTA.idSituacao = SITUACAO.idSituacao
INNER JOIN MEDICO ON CONSULTA.idMedico = MEDICO.idMedico
INNER JOIN PACIENTE ON CONSULTA.idPaciente = PACIENTE.idPaciente
INNER JOIN ESPECIALIDADE ON MEDICO.idEspecialidade = ESPECIALIDADE.idEspecialidade





